// Seed data transcribed from brands/<brand>/gaps.md registers (updated 2026-07-07).
// Ledger entries generated from source CSV/XLSX files by scripts/extract-entries.mjs.
// This is the starting dataset; all edits live in localStorage / cloud and travel via sync or export/import.
import { genLedgers } from './entries.gen'

export const SEED_VERSION = 2

export const seedData = {
  version: SEED_VERSION,
  savedAt: '2026-07-10',
  brands: [
    {
      id: 'aoki',
      name: 'Aoki',
      sub: 'Aoki Mobility Pvt Ltd · POC Prashant',
      updated: '2026-07-07',
      lastReviewed: '2026-07-07',
      position:
        "AOKI 10-Jun-26 ledger: due ₹8,12,960 (32 invoices / 82 bikes / 15 payments, ties to the rupee). BCH net ≈ ₹5,36,880 after all promised credits (fallback ₹6,86,880 excl. ₹1.5L marketing). None of the approved credits issued as CN documents yet — approval ≠ credit.",
      theirBal: { amount: 812960, label: "AOKI ledger 10-Jun-26" },
      ourBal: { amount: 536880, label: 'BCH net after credits (fallback ₹6,86,880)' },
      recov: { amount: 276080, text: '₹2,76,080 credits pending (+ ₹9.9k staff incentive + TBD in-kind)' },
      notes:
        'Hard/documentable CNs ≈ ₹1,16,080 (rows 1–5,7). Cadence CN (#5) & marketing (#6) have NO written approval — top chase priority. Bank statement is the key dependency (dates #9–10, verifies all 15 payments ₹30,12,820).',
      entries: [],
      gaps: [
        { n: 1, title: 'Mamba discount for damaged/battery-issue stock (05-Jan-26 lot of 9)', type: 'discount-pending', amt: 18000, status: 'promised', evidence: 'Approved by Prashant on WhatsApp 05-May-26', action: 'Chase CN document; confirm lump-sum vs per-unit' },
        { n: 2, title: 'Billing incentive balance ₹1,200/bike (82×1,200 − 14,400 paid 18-Dec-25)', type: 'short-credit', amt: 84000, status: 'promised', evidence: 'Approved 05-May-26; ₹14,400 NEFT recd 18-Dec-25 ref IN42535254368383', action: 'Get CN/transfer for 84,000; confirm all 82 bikes qualify' },
        { n: 3, title: 'Sherpa price-difference CN — Z1 ×2 @34,965 vs revised DP 29,925 (2×5,040)', type: 'credit-note-pending', amt: 10080, status: 'promised', evidence: 'Approved 05/14-May-26 ("CN on Sherpa already approved")', action: 'Get CN document; confirm exact figure' },
        { n: 4, title: 'Flex GO discount CN — ₹2,000/unit × 2 (08-Dec-25 billing)', type: 'credit-note-pending', amt: 4000, status: 'promised', evidence: 'Approved 14-May-26', action: 'Get CN document' },
        { n: 5, title: 'Cadence model CN — ₹2,000/unit × 2 (30-Jan-26, price-war model)', type: 'credit-note-pending', amt: 4000, status: 'open', evidence: 'NOT approved in writing; rate conveyed verbally 12-Jun-26', action: 'Get written approval FIRST, then CN document' },
        { n: 6, title: 'Marketing support payout (₹1.5L/month agency plan)', type: 'dispute', amt: 150000, status: 'open', evidence: 'No acknowledgement from AOKI in chat; owner instruction 12-Jun-26', action: 'Get written confirmation before next lump-sum payment' },
        { n: 7, title: 'Product-failure reimbursement — 2 failed Electronic City bikes (logistics+CC+handling)', type: 'reconciliation-difference', amt: 6000, status: 'open', evidence: 'Claim emailed to Prashant 29-Jun-26; not yet approved', action: 'Chase approval' },
        { n: 8, title: 'Salesman incentive transfer — Sales Champions scheme (direct to staff)', type: 'reconciliation-difference', amt: 10300, amtText: '10,300 claimed / 9,900 itemised', status: 'promised', evidence: 'Approved 05-May-26; claim submitted 19-Feb-26 (Iqbal 3,000 / Mujahied 900 / Sravan 500 / Suma 5,500)', action: 'Reconcile 10,300 vs 9,900 FIRST, then chase transfer to staff' },
        { n: 9, title: 'First payment date mismatch — receipt 31-Oct-25 vs AOKI logs 23-Oct-25 (₹76,020)', type: 'reconciliation-difference', amt: 0, amtText: '0 (timing)', status: 'verify', evidence: 'Txn 2154348902; AOKI 05-Feb snapshot', action: 'Align via bank statement' },
        { n: 10, title: 'Two undated payments (₹2,00,000 + ₹2,50,000) bracketed Feb/Mar-26, no chat receipts', type: 'documentation-gap', amt: 0, amtText: '0 (dating)', status: 'verify', evidence: 'Fall between AOKI 05-Feb & 30-Mar snapshots', action: 'Date from bank statement; finish payments.csv' },
        { n: 11, title: 'Damaged Mamba recall — ~9 units + 3 sent to Gautam (only 1 acknowledged)', type: 'operational-warranty', amt: null, amtText: 'TBD (+ CN)', status: 'promised', evidence: '"Will recall all" — Prashant 28-Mar-26', action: 'Pickup of ~9 units + CN; CN for all 3 Gautam units' },
        { n: 12, title: 'Digital display at store (in kind)', type: 'operational-warranty', amt: null, amtText: 'TBD (in-kind)', status: 'open', evidence: '"Under process" — 14-May-26', action: 'Get installation date' },
        { n: 13, title: 'Bajaj Finance EMI tie-up (in kind)', type: 'operational-warranty', amt: null, amtText: 'TBD (in-kind)', status: 'open', evidence: '"Under process" — 14-May-26; 12 Ghost enquiries waited on EMI', action: 'Get go-live date' },
        { n: 14, title: 'Annual support plan — 600 bikes to Mar-27, "all support"', type: 'documentation-gap', amt: null, amtText: 'TBD', status: 'promised', evidence: 'Stated 05-May-26; "shared by mail" 14-May-26', action: 'Verify mail received; get plan in writing' },
        { n: 15, title: 'Stock refill (60 units) — Ghost & CR by 15-Jun, full refill by 20-Jun', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: 'Prashant commitment', action: 'Hold to dates before releasing next lump sum' },
        { n: 16, title: 'Balance not yet agreed — AOKI ₹8,12,960 vs BCH net ₹5,36,880', type: 'balance-unconfirmed', amt: 276080, amtText: '2,76,080 (gap between figures)', status: 'open', evidence: "AOKI 10-Jun-26 ledger vs BCH recon; Prashant 22-May-26 'with all your CN — 6 Lac'", action: 'Reconcile once all CN documents issued' },
      ],
    },
    {
      id: 'cultsport',
      name: 'Cultsport',
      sub: 'Cultsport (Curefit, ex-Cultgear) · POC Mani Gandan',
      updated: '2026-07-07',
      lastReviewed: '2026-07-07',
      position:
        "Brand official (Curefit statement) ₹27,03,388 closing 25-May-26 vs BCH line-items ₹25,71,988 to 28-Jun-26 (₹25,88,950 at same cut-off) → BCH ~₹1.14L below brand. Srinu's headline box ₹54,08,576 is internally broken — do NOT settle against it. Defensible working payable ≈ ₹25.7–27.0L.",
      theirBal: { amount: 2703388, label: 'Curefit statement 25-May-26' },
      ourBal: { amount: 2571988, label: "BCH line-items (Srinu xlsx, 236 rows) 28-Jun-26" },
      recov: { amount: 3404124, text: '₹34,04,124 quantified gap (incl. ₹28.37L internal ₹54L-box correction)' },
      notes:
        "Mani = Manish = Mani Gandan (one person). Srinu = BCH's own accountant — the ₹54L error is in BCH's file. Don't double-claim: 15-Oct-25 AR memos ₹2,33,609 + Feb-26 batch ₹2,61,162 may already cover #3/#4/#7. Everything on email going forward.",
      entries: [],
      gaps: [
        { n: 1, title: "Internal error in Srinu's xlsx: headline ₹54,08,576 vs line-items ₹25,71,988 (drops ₹27.08L real payments, adds ₹1.29L phantom purchases)", type: 'documentation-gap', amt: 2836588, status: 'open', evidence: 'Summary box vs 236 rows re-totalled; 53 bank payments each with unique refs (01-Jul-26 working paper)', action: 'Fix box to equal rows. Do NOT pay against ₹54L — would overpay ~₹27L' },
        { n: 2, title: 'Reconciliation difference vs brand: BCH ₹25,88,950 vs Curefit ₹27,03,388 (25-May cut-off)', type: 'reconciliation-difference', amt: 114438, status: 'verify', evidence: 'Curefit Customer Statement 25-May-26 vs xlsx rows', action: 'Reconcile line-by-line; gap = CD/CN booked by BCH not yet passed by brand' },
        { n: 3, title: "CD-Pending carried on brand's 05-May-25 ledger image", type: 'discount-pending', amt: 297173, status: 'verify', evidence: 'Brand ledger image 05-May-25 (chat)', action: 'Verify whether later passed (Jul-25 / 15-Oct-25 / Feb-26 memo batches); credit balance' },
        { n: 4, title: 'Old Due adjustment on same brand image', type: 'discount-pending', amt: 62883, status: 'verify', evidence: 'Brand ledger image 05-May-25 (chat)', action: 'Confirm credited' },
        { n: 5, title: 'GST-difference credit note (7% GST diff) — "exact calc will share"', type: 'credit-note-pending', amt: 113000, amtText: '~1,13,000', status: 'open', evidence: 'WhatsApp Mani, 31-Oct-25', action: 'Confirm CN issued and passed' },
        { n: 6, title: 'Power/Brave/Throne liquidation pricing correction — CN 73701', type: 'credit-note-pending', amt: 225000, status: 'verify', evidence: 'Mani admitted "flat ₹1,300 incl. tax, our mistake" 19-Dec-25; CN 73701 issued 30-Dec-25', action: 'Verify CN reflects flat ₹1,300 incl. tax; BCH claims extra 16% → net ₹1,096' },
        { n: 7, title: 'FOC short-fall (₹15,857 + ₹8,499 + ₹12,123 + Karas)', type: 'short-credit', amt: 36479, amtText: '~36,479', status: 'verify', evidence: 'Chat mid-2024; partly settled in stock (Karas)', action: 'Confirm remaining balance credited or replaced' },
        { n: 8, title: 'FOC % dispute — BCH says 13%, brand says 12%', type: 'dispute', amt: null, amtText: '~1% of FOC base (TBD)', status: 'open', evidence: 'Chat Oct-25; unreconciled', action: 'Get agreed FOC % in writing; quantify differential' },
        { n: 9, title: 'Marketing reimbursement (CRPF event) — no pre-approved designs/docs', type: 'dispute', amt: 50000, status: 'rejected', evidence: 'Chat Jul-24', action: 'Lost for lack of documents; drop unless docs surface' },
        { n: 10, title: 'CD is timing-dependent: 8% if paid ≤7 days, 4% past 30 days — brand flagged late payments', type: 'dispute', amt: null, amtText: 'TBD (per late month)', status: 'open', evidence: 'JULY scheme circular + brand flag 14-Nov-24', action: 'Confirm each 8% Tally posting has a ≤7-day payment, else brand can claw 8%→4%' },
        { n: 11, title: 'Entity migration Cultgear→Cultsport/Curefit — opening balance carry-over not documented', type: 'documentation-gap', amt: null, amtText: 'TBD', status: 'verify', evidence: 'Payee changed 27-Feb-26 (₹3L to "CULTSPORT" via ICICI); no carry-over record', action: 'Get Cultgear-era closing confirmed in writing as Cultsport opening' },
        { n: 12, title: 'Second related account "Bharath Cycle Centre (BCC)" — keep separate', type: 'balance-unconfirmed', amt: 1601590, status: 'verify', evidence: 'Older Cultsport AR report for BCC (closing ₹16,01,590)', action: 'Confirm if BCC live; keep accounts cleanly separated' },
        { n: 13, title: 'Reconciliation anchor — BCH claims account ZERO as on 21-Aug-2024', type: 'balance-unconfirmed', amt: 0, amtText: '0 (anchor)', status: 'verify', evidence: 'BCH told Mani 25-Feb-26; he replied "will check"', action: 'Get zero-point confirmed in writing; pre-21-Aug-24 then drops out' },
        { n: 14, title: 'No signed final ledger in ~2 years; Jan-25 auditor Google Meet abandoned', type: 'documentation-gap', amt: null, amtText: 'TBD', status: 'open', evidence: 'Chat; ~2-year history', action: 'Complete the meeting; lock a mutually-signed statement' },
        { n: 15, title: 'Replacement/warranty stock — 3 Monstro, Cult e-cycle return, damaged frames, foldable part', type: 'operational-warranty', amt: null, amtText: 'in-kind', status: 'verify', evidence: 'Chat 2024–25', action: 'Confirm each item replaced or credited' },
      ],
    },
    {
      id: 'emotorad',
      name: 'EMotorad',
      sub: 'Inkodop Technologies · Sandeep (NSH) / Jaya (RSM South)',
      updated: '2026-07-07',
      lastReviewed: '2026-07-07',
      position:
        'Hub (folio 666) ₹88,87,251.90 Dr as of 17-Jun-26 + dormant BCC (folio 121) ₹3,48,345.92 Dr → combined gross payable ≈ ₹92,35,598 (18-Jun-26). Supersedes EM BIZ app ₹70.1L and old ₹35–43L estimate. Net payable lower once unredeemed CNs post — needs a fresh signed both-folio SOA. BCH #1 brand (~50–60% of revenue).',
      theirBal: { amount: 9235598, label: 'Combined gross Hub+BCC 18-Jun-26' },
      ourBal: { amount: null, label: 'Net pending fresh signed both-folio SOA' },
      recov: { amount: 684314, text: '₹6,84,314 quantified (+ TBD/in-kind; structural exposure up to ₹74L)' },
      notes:
        "Two docs close the money side: EM's signed SOA for BOTH folios as of one date + BCH's CREDIT NOTES.xlsx + bank statement. Largest exposures (verify, not additive): #19 ₹74L BCC CN duplication · #24 ₹39.9L sales-CN legitimacy · #21 ₹31L Jan-25 invoice dump · #2 ₹10L unrecorded payment. Root cause: invoices→Hub, payments+CN→Centre.",
      entries: [],
      gaps: [
        { n: 1, title: 'Combined gross payable unconfirmed by fresh signed SOA — Hub ₹88.87L + BCC ₹3.48L', type: 'balance-unconfirmed', amt: 9235598, status: 'verify', evidence: '17-Jun-26 · open-items-register', action: "Obtain EM's current signed SOA for BOTH folios (121+666) as of one date" },
        { n: 2, title: 'Unrecorded ₹10,00,000 direct payment (pre-dates Apr-25 ledger start)', type: 'reconciliation-difference', amt: 1000000, status: 'verify', evidence: '06-Jan-25 · register #3', action: 'Match against BCH bank statement + EM FY24-25 SOA' },
        { n: 3, title: 'Deepak ₹49,000 debited by BCH, not received/credited by EM', type: 'reconciliation-difference', amt: 49000, status: 'open', evidence: '15-Jan-25 (D L6847)', action: 'Trace in FY24-25 ledger' },
        { n: 4, title: 'Sanjay-B ₹10,000 receipt (Jun-24) not reflected', type: 'reconciliation-difference', amt: 10000, status: 'open', evidence: '18-Aug-25 (D L8531)', action: 'Verify posting' },
        { n: 5, title: 'Trex-Pro discount CN — ₹4,500/₹4,000 per bike + ₹5K delta; 26 units liquidated', type: 'credit-note-pending', amt: 200000, status: 'promised', evidence: 'Aug→Dec-25; Sandeep 02-Dec-25 "no positive response"', action: 'Largest CN dispute — get quantum + credit; attach Sandeep-Sinha "liable to get CN" email' },
        { n: 6, title: 'Sravan manpower support ₹25k × 6 (approved 25-Aug-25) — appears NOT credited', type: 'credit-note-pending', amt: 150000, status: 'promised', evidence: '25-Aug-25 (S L492, D L9283)', action: 'Confirm all 6 months credited' },
        { n: 7, title: 'Thailand-trip CN — benefit-in-lieu promised then "no CN for Thailand" (contradictory)', type: 'credit-note-pending', amt: null, amtText: 'TBD', status: 'promised', evidence: '31-Jan-26 (J L278) vs (S L2264)', action: 'Resolve contradiction; get written position' },
        { n: 8, title: '50%-ticket / one-side-vs-both-side CN — approved 06-Apr-26, finance "to process"', type: 'credit-note-pending', amt: 11233, status: 'promised', evidence: '01-Apr-26 (J L501-517)', action: 'Confirm finance processed' },
        { n: 9, title: 'CD shortfall Mar-26 — 4% × ₹35L = ₹1.40L expected vs ₹1.05L issued', type: 'short-credit', amt: 35000, status: 'verify', evidence: 'Mar-26 (J L393); CNs MHCN2627-00176/00177', action: 'Match per-deal; claim ₹35k short' },
        { n: 10, title: 'JFM scheme (250 units claimed) — "JFM not through"', type: 'credit-note-pending', amt: null, amtText: 'TBD', status: 'rejected', evidence: 'Apr-26 (J L520)', action: 'Confirm denial / escalate' },
        { n: 11, title: 'FY22-23 legacy credits — ₹78,778 + LIL-E 5K×2 + X2 ₹10k + EMX/Trex ₹3k', type: 'credit-note-pending', amt: 100000, status: 'open', evidence: 'Jun-23 (D L515,358,503)', action: 'Chase stale credit or write off' },
        { n: 12, title: 'Missing bills SP/394 (₹4,997) & SP/395 (₹5,994)', type: 'documentation-gap', amt: 10991, status: 'open', evidence: 'Jun-23 (D L516)', action: 'Obtain bills / credit' },
        { n: 13, title: 'Paytail ₹5,000 short on 2 financed cycles — never confirmed closed', type: 'short-credit', amt: 5000, status: 'open', evidence: 'Jul-23 (D L766)', action: 'Confirm settlement' },
        { n: 14, title: 'Mr. Sunil exchange logistics ₹12,000 + ₹1,500 ("you\'ll take care")', type: 'short-credit', amt: 13500, status: 'open', evidence: 'Nov-23 (B L1698)', action: 'Claim reimbursement' },
        { n: 15, title: 'Gaurav giveaway CN never added', type: 'credit-note-pending', amt: null, amtText: 'TBD', status: 'promised', evidence: 'Apr-24 (C L3652)', action: 'Get CN issued' },
        { n: 16, title: 'Movement-of-Fun / Electrathon event expenses + jerseys', type: 'credit-note-pending', amt: 10655, status: 'open', evidence: 'Jan-24 (B L2646)', action: 'Claim ₹10,655 + jersey value (TBD)' },
        { n: 17, title: 'Security deposit "Chanakya" ₹3,50,000 (Apr-23) — still on EM books / refundable?', type: 'balance-unconfirmed', amt: 350000, status: 'verify', evidence: 'FY23 · reconciliation A/D3', action: 'Confirm status; recover on exit' },
        { n: 18, title: '41 write-off entries ₹79,594 (BCC) — by whose authority?', type: 'documentation-gap', amt: 79594, status: 'verify', evidence: 'FY24-25 (BLR.xls)', action: 'Get authorisation trail' },
        { n: 19, title: '₹74L of BCC credit notes — possibly duplicated/mis-applied vs Hub folio', type: 'reconciliation-difference', amt: 7404273, status: 'verify', evidence: 'FY24-25 · register #20', action: "Cross-check both folios' CN lists vs entitlement (high exposure)" },
        { n: 20, title: 'Two-folio mis-posting — invoices→Hub, payments+CN→Centre; neither folio standalone correct', type: 'reconciliation-difference', amt: null, amtText: 'TBD (structural)', status: 'open', evidence: 'chronic (D L6004, L9207)', action: 'Reconcile both folios as of one date; one-folio rule going forward' },
        { n: 21, title: 'BCC −27.5L → +3.77L Jan-25 invoice dump (₹31L) — verify not double-billed vs Hub', type: 'reconciliation-difference', amt: 3100000, status: 'verify', evidence: 'Jan-25 · reconciliation D2', action: 'Verify the Jan invoices are legitimate' },
        { n: 22, title: 'Opening ₹3,20,023 (Apr-2023) — origin/validity unconfirmed', type: 'balance-unconfirmed', amt: 320023, status: 'verify', evidence: 'Apr-23 · reconciliation D4', action: 'Trace opening entry' },
        { n: 23, title: 'inv 27-EM-2526-02671 — POD/physical copy missing, folio mismatch (₹2,19,990 Dr)', type: 'documentation-gap', amt: 219990, status: 'open', evidence: '26-May-25 (D L9207)', action: 'Get POD' },
        { n: 24, title: '58 sales-invoice credits (₹39.9L) = returns/sales-CN — confirm each legitimate', type: 'reconciliation-difference', amt: 3986508, status: 'verify', evidence: 'FY25-26 · register #24', action: 'Verify each against a real return' },
        { n: 25, title: '35 ShopSe/Paytm/Bajaj finance settlements — "not reflecting"', type: 'reconciliation-difference', amt: null, amtText: 'TBD', status: 'open', evidence: 'recurring · reconciliation B/D7', action: 'Confirm each reflected on ledger' },
        { n: 26, title: 'EM BIZ app balance ≠ actual ledger', type: 'balance-unconfirmed', amt: null, amtText: 'TBD', status: 'open', evidence: '03-Feb-25 & 16-Apr-25 (D L7687, S L253)', action: 'Reconcile app to signed SOA' },
        { n: 27, title: 'CD% friction — 4% asked, 2-3% given; official ceiling 3% advance / 1.5% within 30 days', type: 'documentation-gap', amt: null, amtText: 'TBD', status: 'open', evidence: 'recurring (S L2043, J L368)', action: 'Get written CD policy; track which 4% deals honoured' },
        { n: 28, title: 'BCH-raised Debit Notes 25-Oct-23 (lil-e box, emx demo, godown stock, display, DN 02)', type: 'credit-note-pending', amt: null, amtText: 'TBD', status: 'open', evidence: '25-Oct-23 · reconciliation D10', action: 'Confirm EM accepted each DN' },
        { n: 29, title: '3% CD on ₹15L (30-Oct-25) — ~₹45,000 CN, no PDF tied to it', type: 'short-credit', amt: 45000, status: 'verify', evidence: '30-Oct-25 · findings B7', action: 'Match to a CN' },
        { n: 30, title: '"125K" CN vs actual ₹51,242 — cleared via MHCN2526-02200 but amount gap', type: 'short-credit', amt: null, amtText: 'TBD', status: 'verify', evidence: '03-Nov-25 · findings B9', action: 'Reconcile the amount gap' },
        { n: 31, title: 'Online/festive per-unit price-protection CN (GOAT/Freedom/Diwali) — several never confirmed', type: 'credit-note-pending', amt: null, amtText: 'TBD', status: 'open', evidence: 'Jul–Oct-25 · CN register §B', action: 'Units × per-unit table vs CNs; get "ONLINE DISCOUNT" sheet (email-02)' },
        { n: 32, title: 'Surya Roshni promo X1 — 10 received, 6 issued, 4 unaccounted', type: 'short-credit', amt: null, amtText: 'TBD', status: 'open', evidence: '18-Dec-25 (F L9304)', action: 'Account for 4 units (stock + ₹)' },
        { n: 33, title: 'STX over-shipment — 2 ordered → 4 received (over-billing)', type: 'dispute', amt: null, amtText: 'TBD', status: 'open', evidence: '29-Sep-25 (F L8997)', action: 'Return / reverse 2 units' },
        { n: 34, title: 'X3 over-shipment — 2 ordered → 3 received (over-billing)', type: 'dispute', amt: null, amtText: 'TBD', status: 'open', evidence: '21-Mar-24 (C L3250)', action: 'Reverse 1 unit' },
        { n: 35, title: '~20+ customers never invoiced by EM (GST input-credit risk)', type: 'documentation-gap', amt: null, amtText: 'TBD', status: 'open', evidence: 'recurring · register #54', action: 'Get all PODs/invoices for received stock' },
        { n: 36, title: 'PODs missing for many invoices (uploaded to GST portal, copies never sent)', type: 'documentation-gap', amt: null, amtText: 'TBD', status: 'open', evidence: 'recurring to Nov-25 · register #55', action: 'Collect physical POD/invoice copies' },
        { n: 37, title: 'Brake systemic defect (#109192) — pads dead 527 km; correct parts NOT dispatched', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: '01-Jun-26 (S L2224, J L625)', action: 'Escalate root-cause + dispatch correct parts' },
        { n: 38, title: 'Rajita Nair (Viper) — oil leak/brakes fail, wrong product sent, live CEO+LinkedIn escalation', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: '16-Jun-26 (S L2320)', action: 'Close live public escalation' },
        { n: 39, title: 'Bhargav (Viper) display lost in courier (motor shipped instead, 20+ days)', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: '11-Jun-26 · service-issues #2', action: 'Confirm replacement display delivered' },
        { n: 40, title: 'T-Rex+ lot missing headset spacers — whole lot unsellable', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: 'Sep-25 · register #38', action: 'Claim replacement spacers / CN for dead stock' },
        { n: 41, title: '1,800+ free services absorbed + ~₹700/delivery & ₹1,000/Desire-kit', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: '10-Mar-26 (S L1389)', action: 'Claim service-cost recovery / monthly CN' },
        { n: 42, title: 'Warranty walk-backs — Doodle range, display 6-mo only, battery "tampered sticker" denial', type: 'dispute', amt: null, amtText: 'TBD', status: 'open', evidence: 'various · service-issues case studies', action: 'Get published warranty matrix; reopen denied claims' },
        { n: 43, title: 'Viper supply failure — 38+ prebookings, refunds/cancellations, ETA slipped to end-Jul-26', type: 'dispute', amt: null, amtText: 'TBD', status: 'open', evidence: 'Mar–Jun-26 (S L2075-2307)', action: 'Recover deposits / secure supply' },
        { n: 44, title: 'X1 black with X2 display (10 units) pending "since long"', type: 'dispute', amt: null, amtText: 'TBD', status: 'open', evidence: '(J L644, S L2290)', action: 'Deliver or cancel-and-credit' },
        { n: 45, title: 'Wrong dispatch 01-May-26 — of 46 bikes, 23 never ordered (~40% fill)', type: 'dispute', amt: null, amtText: 'TBD', status: 'verify', evidence: '01-May-26 (S L1792); owner marked SOLVED as genuine stock', action: 'Verify no over-bill / return CN on the 23 unordered' },
        { n: 46, title: 'Lead-generation system (Phase-1 Feb-26 / Samrat app) — promised, never delivered', type: 'dispute', amt: null, amtText: 'TBD', status: 'open', evidence: '(J L323, S L1212)', action: 'Claim delivery or compensation' },
        { n: 47, title: 'EM Trailblazers Club benefit — undefined for BCH', type: 'documentation-gap', amt: null, amtText: 'TBD', status: 'open', evidence: '18-Aug-25 (F L8549)', action: 'Get scheme terms in writing' },
        { n: 48, title: 'Consumer-court case filed (legal exposure)', type: 'dispute', amt: null, amtText: 'TBD', status: 'open', evidence: '23-Jul-25 · register #34', action: 'Track case; seek EM indemnity' },
      ],
    },
    {
      id: 'hornback',
      name: 'Hornback',
      sub: 'Hornback E Mobility (ZOP) · POC Aditya Vashishta',
      updated: '2026-07-07',
      lastReviewed: '2026-07-07',
      position:
        'BCH owes Hornback ₹4,65,915.19 per official SOA (to 30-Jun-26). Ledger ties out: invoiced net of CN ₹26,73,518.19 − received ₹22,07,603 = balance. Clean ledger; gaps are discount/documentation-driven. Main dispute: 15% vs 20% discount (~₹1.3–1.4L).',
      theirBal: { amount: 465915.19, label: 'Hornback SOA to 30-Jun-26' },
      ourBal: { amount: null, label: 'Not yet reconciled vs BCH books/bank' },
      recov: { amount: 170000, text: '₹1.70–2.00L (Dispute #1 ~₹1.3–1.4L + #2 ~₹40–60k + TBD in-kind)' },
      notes:
        'Dispute #1 hinges entirely on a WRITTEN 20% commitment — chats only show Aditya\'s 15% calc vs Syed\'s verbal "20%". Recoverables REDUCE the payable, not cash back. Pay only to SBI CC 43842889558 (old HDFC acct was Lucifer\'s — verify no misrouting).',
      entries: [],
      gaps: [
        { n: 1, title: 'Discount given at 15% but deal understood as 20% — ~5% gap on ~₹28L bike value', type: 'dispute', amt: 130000, amtText: '1,30,000–1,40,000', status: 'open', evidence: '07-Nov-25 chat L1056 (Aditya 15% calc) vs L1059 (Syed: "Apna baat 20% pe hua tha")', action: 'Produce written/agreed 20% scheme letter/email; without it Hornback may honour only 15%' },
        { n: 2, title: 'Discount calculated only "from July-2025"; pre-July purchases (≈₹4.16L) almost no CN', type: 'short-credit', amt: 40000, amtText: '40,000–60,000', status: 'open', evidence: 'CN148 (09-Dec-25) calc starts Jul-25; only CN-177 ₹18,298 pre-July', action: 'Ask Hornback to confirm early invoices also get their % / issue balance CN' },
        { n: 3, title: 'Foldable Hornback (M1) credit note pending — not yet issued', type: 'credit-note-pending', amt: null, amtText: 'TBD', status: 'promised', evidence: '29-Dec-25 chat L1078 ("foldable hornback ka CN pending hai")', action: 'Chase M1 CN; quantify eligible qty × rate' },
        { n: 4, title: '₹400-per-cycle support referenced by POC — not confirmed in issued CNs', type: 'discount-pending', amt: null, amtText: 'TBD', status: 'verify', evidence: '02-Oct-25 chat L933–937', action: 'Reconcile ₹400 × cycle count against the 8 CNs; claim shortfall' },
        { n: 5, title: '₹1,500 on "Xpand" confidential support — not verified as credited', type: 'discount-pending', amt: 1500, status: 'verify', evidence: '20-May-25 chat L780', action: 'Verify ₹1,500 posted to ledger/CN' },
        { n: 6, title: 'CNs issued late in batch (CN148/222/223/264/265) — confirm all on ledger', type: 'documentation-gap', amt: 0, amtText: '0 (verify completeness)', status: 'verify', evidence: 'Batch dated 02-May-26 (PDFs); ledger shows CN148/222/223/264/265 + CN031/032', action: 'Confirm every promised discount CN is on the SOA' },
        { n: 7, title: 'Standardisation / warranty-barcode issues (Lucifer era) — carry-over check for ZOP', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: 'Lucifer-era chat L452–456', action: 'Confirm ZOP bikes have warranty barcode/docs; raise open claims' },
        { n: 8, title: "Payment completeness not independently confirmed vs BCH's bank/UTR record", type: 'balance-unconfirmed', amt: null, amtText: 'TBD', status: 'verify', evidence: 'payments.csv (26 receipts = ₹22,07,603, ties to SOA)', action: 'Compare BCH outgoing bank/UTR list vs SOA' },
        { n: 9, title: 'Closing ₹4,65,915.19 per Hornback SOA only — not confirmed against BCH ledger', type: 'balance-unconfirmed', amt: 465915, status: 'verify', evidence: '08-Jun-26 · SOA statement_BHARATHCYCLEHUB (6).pdf', action: 'Reconcile against BCH books; obtain signed balance confirmation' },
      ],
    },
    {
      id: 'lucifer',
      name: 'Lucifer',
      sub: 'Lucifer / Lucifire Bikes · POC Prashant',
      updated: '2026-07-07',
      lastReviewed: '2026-07-07',
      position:
        "Lucifer ledger closing 02-Jul-26 = ₹18,48,717 Dr (after DIS-99 & DIS-100). BCH true net after pending discounts ≈ ₹15.0–15.2L (firm ≈ ₹15,17,952). Discounts are invoice-wise: rate × (invoice ÷ (1+GST)); electric 5% GST, regular 12%. Rate timeline: 20% → 18% (Jun-25→Mar-26) → 17% claimed FY26-27 (unconfirmed).",
      theirBal: { amount: 1848717, label: 'Lucifer ledger 02-Jul-26' },
      ourBal: { amount: 1517952, label: 'BCH true net (firm; best-case ₹14,95,825)' },
      recov: { amount: 354767, text: '₹3,54,767 firm (+ ₹150/cycle TBD, ₹1,875 unloading, in-kind)' },
      notes:
        'Already CLEARED 02-Jul — do NOT re-claim: DIS-99 ₹45,720 (18% on LB 814/815/849) and DIS-100 ₹3,30,049 (17% on LB 41/272/281, rate query open). CN-48 ₹45,218 settles the 5-box LB/0364 short-delivery. 11-Jun ₹5L (Rcpt 363) now posted.',
      entries: [],
      gaps: [
        { n: 1, title: 'New bill LB/26-27/0363 (₹17,82,742, 30-Jun-26) — discount NOT raised yet. Biggest item.', type: 'discount-pending', amt: 288634, amtText: '2,88,634 @17% (₹3,05,613 @18%)', status: 'open', evidence: '02-Jul-26 ledger §2 row A', action: 'Ask Lucifer to raise CD journal on 0363; confirm 17% vs 18% rate' },
        { n: 2, title: 'Old bill LB 689 (₹1,35,452) — 18% CD shown 12-Mar-26 then withdrawn, never re-credited', type: 'discount-pending', amt: 21769, status: 'open', evidence: '02-Jul-26 ledger §2 row B; discounts.md §3a/§4', action: 'Claim CD; apply per-invoice GST (5% vs 12%)' },
        { n: 3, title: 'Old bill LB 690 (₹88,813, 16 kids bikes) — no CD ever passed. Kids steel may be ZERO-discount.', type: 'discount-pending', amt: 14274, status: 'verify', evidence: '02-Jul-26 ledger §2 row B; discounts.md §1', action: 'Confirm if 690 qualifies; if kids-steel, drop' },
        { n: 4, title: 'Old bill LB 365 (₹26,539, kids bill) — no CD. Flagged kids/zero-discount.', type: 'discount-pending', amt: 4265, status: 'verify', evidence: '02-Jul-26 ledger §2 row B', action: 'Confirm eligibility; if kids-steel, drop' },
        { n: 5, title: 'Old bill LB 468 (₹11,340, 1 bike) — CD never passed', type: 'discount-pending', amt: 1822, status: 'open', evidence: '02-Jul-26 ledger §2 row B; discounts.md §4', action: 'Claim CD on LB/0468' },
        { n: 6, title: 'DIS-100 credited at 17% while DIS-99 (same day) at 18% — on taxable ₹19.4L', type: 'short-credit', amt: 19415, status: 'verify', evidence: '02-Jul-26 ledger §1 & §2 row C', action: 'Get correct rate in writing; if 18%, claim the 1% gap' },
        { n: 7, title: 'LB 600 short-credited — DIS-304 ₹72,895 vs ₹75,607 @18%', type: 'short-credit', amt: 2712, status: 'open', evidence: '02-Jul-26 ledger §2 row D', action: 'Claim balance CD on LB/0600' },
        { n: 8, title: '₹150/cycle rebate — seen on LB 364 (DIS-210); other bills?', type: 'discount-pending', amt: null, amtText: 'TBD (₹150 × units)', status: 'verify', evidence: '02-Jul-26 ledger §2 row E; ₹150/cycle on 100+ orders', action: 'Confirm applicability; claim per qualifying bill' },
        { n: 9, title: 'DIS-210 under-credited by ₹1,050 (LB/0364 + ₹19,500 transport)', type: 'short-credit', amt: 1050, status: 'open', evidence: '13-Jun-26 discounts.md §3c', action: 'Claim ₹1,050 shortfall' },
        { n: 10, title: 'DIS-90 under-credited by ₹539 (LB/0156+0175)', type: 'short-credit', amt: 539, status: 'open', evidence: '13-Jun-26 discounts.md §3b; screenshot 00000229', action: 'Claim ₹539 shortfall' },
        { n: 11, title: '₹1,875 unloading paid by BCH on LB/0364 (handwritten on invoice 283)', type: 'reconciliation-difference', amt: 1875, status: 'open', evidence: '13-Jun-26 findings.md', action: 'Claim reimbursement (not CD)' },
        { n: 12, title: '17-Feb-26 ₹3,00,000 (Rcpt 1203) credited by Lucifer, NO proof in chat', type: 'documentation-gap', amt: 0, status: 'verify', evidence: '13-Jun-26 findings.md; payments.csv row 9', action: 'Verify in BCH bank statement (in our favour if genuine)' },
        { n: 13, title: '7–10 cycles chain/chainwheel defects (18-Nov-25) — replacements promised, not credited', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: '13-Jun-26 findings §Goods 3', action: 'Obtain CN / physical replacement' },
        { n: 14, title: 'Wrong wheel + missing chain cover (13-Feb-26) — replacement promised, not settled', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'open', evidence: '13-Jun-26 findings §Goods 4', action: 'Obtain replacement / CN' },
        { n: 15, title: 'Max-dealer cross-dispatch (2-Nov-25) — who-got-what never reconciled', type: 'reconciliation-difference', amt: null, amtText: 'TBD', status: 'open', evidence: '13-Jun-26 findings §Goods 5', action: 'Reconcile dispatch split with Lucifer' },
        { n: 16, title: 'Balance unconfirmed — Lucifer ₹18,48,717 vs BCH true net ≈ ₹15.0–15.2L', type: 'balance-unconfirmed', amt: 0, status: 'verify', evidence: '02-Jul-26 ledger §3', action: 'Get fresh Lucifer statement; reconcile confirmed vs true-net' },
      ],
    },
    {
      id: 'raleigh',
      name: 'Raleigh',
      sub: 'Raleigh / Suncross · Naren International, Ludhiana · POC Mohineesh Kumar',
      updated: '2026-07-07',
      lastReviewed: '2026-07-07',
      position:
        "BCH accepts Naren's closing ₹38,34,108.85 Dr (10-Jun-26 Tally print, verified across 14 prints); BCH net-payable after quantified approved credits ≈ ₹35,68,182.85 (realistic credit pool ₹4.5–5.5L with TBDs). No signed reconciliation exists; FY26-27 shows NIL rebate JVs from Naren.",
      theirBal: { amount: 3834108.85, label: "Naren Tally print 10-Jun-26" },
      ourBal: { amount: 3568182.85, label: 'BCH net after quantified credits' },
      recov: { amount: 265926, text: '₹2,65,926 quantified (realistic pool ₹4.5–5.5L with TBDs)' },
      notes:
        'Scheme/price-backed credits (owner-confirmed) = ₹1,69,587; disputed items ₹96,339 need negotiation. Priorities: corrected G-0266 invoice (#8) and FY26-27 CD JVs (#1/#9); get all verbal 12-Jun terms in writing from Mohineesh. All 34 payments still marked matched_to_bank = pending.',
      entries: [],
      gaps: [
        { n: 1, title: 'CD at revised rates from Apr-26 (4% E-Surge Pro) on G-0106+G-0266+G-0822 — no CD JV in FY26-27', type: 'discount-pending', amt: 68587, status: 'promised', evidence: '12-Jun-26 owner-confirmed terms', action: 'Get CD JV from Naren; base shrinks if G-0266 reversed (#8)' },
        { n: 2, title: 'E-Skarn ₹3,000/set (MS & SS) balance — 17 sets paid only ₹1,000 + 5×29" MS never credited', type: 'credit-note-pending', amt: 49000, status: 'promised', evidence: '12-Jun-26 owner (verbal from Mohineesh); JVs 2000/2015', action: 'Get ₹3,000-both-MS-&-SS in writing; demand balance CN' },
        { n: 3, title: 'Overvolt price difference G-0266 — promised ₹30,000 incl GST, billed ₹34,900 (₹4,900 × 10)', type: 'credit-note-pending', amt: 49000, status: 'promised', evidence: '12-Jun-26 owner (verbal); G-0266 13-Apr-26', action: 'Demand CN at ₹30k rate' },
        { n: 4, title: 'Undelivered E-Skarn — G-0106: 1×27.5" @₹43,571+5% billed 06-Apr-26, never delivered', type: 'short-credit', amt: 45750, status: 'open', evidence: 'Photos + barcode mismatch sent 13/14-Apr-26 ("Oki sir"); no CN', action: 'Demand CN for undelivered unit' },
        { n: 5, title: 'Contested debit notes — DN-007 ₹5,040 (never explained) + DN-198 ₹20,549 (retro rate-diff)', type: 'dispute', amt: 25589, status: 'open', evidence: 'DN-007 07-Apr-25; DN-198 25-Oct-25', action: 'Contest both; demand reversal / explanation' },
        { n: 6, title: 'Bulk-order ₹1,000/bike support — "1000 / Done", later withdrawn (est. 25 units)', type: 'dispute', amt: 25000, status: 'open', evidence: '31-May-25 "1000/Done"; withdrawn per Syed 21-Aug-25 protest', action: 'Confirm qualifying order with Mohineesh; claim it' },
        { n: 7, title: '24" E-Surge ₹500 × 6 bikes (on G-1503)', type: 'commitment-pending', amt: 3000, status: 'promised', evidence: '18-May-26 Mohineesh: "500 rs per bike, only for you sir"', action: 'Demand JV/CN' },
        { n: 8, title: 'G-0266 price reversal committed — E-Surge Pro billed above same-month G-0106 rates', type: 'dispute', amt: null, amtText: 'TBD (~30–60k + GST)', status: 'promised', evidence: 'Raised 28-Apr-26; reversal committed 12-Jun-26 (owner)', action: 'Chase corrected/reversed invoice; check G-0822 pricing too' },
        { n: 9, title: 'CD on E-Surge Eco (3%) + 4% Pro on unscanned FY26-27 invoices (~₹19L billing)', type: 'discount-pending', amt: null, amtText: 'TBD (~40–70k)', status: 'promised', evidence: '12-Jun-26 owner terms', action: "Get invoice copies / Naren's CD working" },
        { n: 10, title: 'E-Surge ₹250/set balance — sets billed Aug-25→Jun-26 not visibly covered', type: 'commitment-pending', amt: null, amtText: 'TBD', status: 'promised', evidence: 'Agreed 21-Aug-25; JVs 797/798/799 (₹45,000 through Jul-25 only)', action: 'Get bill-wise set count / CD working' },
        { n: 11, title: 'Overvolt ₹30k retro on Jul-25 lot — 4 units on G-2427: 4×4,650 less ₹4,000 credited', type: 'commitment-pending', amt: 14600, amtText: 'TBD (~14,600)', status: 'verify', evidence: 'Owner 12-Jun-26; JVs 2000/2015', action: 'Confirm whether price applies retroactively' },
        { n: 12, title: 'CD deviation FY25-26 (2% era) — flagged, not quantified', type: 'discount-pending', amt: null, amtText: 'TBD', status: 'open', evidence: '18-May-26 ("CD deviation aa raha hai")', action: "Get Naren's bill-wise CD working" },
        { n: 13, title: 'E-bike warranty claims — ₹1,45,759 credited so far; full claims report awaited', type: 'operational-warranty', amt: null, amtText: 'TBD', status: 'verify', evidence: 'CN-0183 ₹63,997 + CN-0252 ₹81,762; parts billed @7,895–8,650 vs credited @7,300', action: 'Match every claim vs the two CNs; demand unadjusted balance' },
        { n: 14, title: 'G-4152 box shortage — 1 box short on signed POD', type: 'short-credit', amt: null, amtText: 'TBD', status: 'open', evidence: 'Signed delivery copy 08-Oct-25; no CN traced', action: 'Identify box contents/value, then claim CN' },
        { n: 15, title: 'Two ledger receipts with NO chat receipt — 07-Mar-26 ₹3L (#7898) + 18-May-26 ₹5L (#1206)', type: 'documentation-gap', amt: 800000, status: 'verify', evidence: 'Naren ledger only; payments.csv rows 24 & 29', action: 'Verify both against BCH bank statement' },
        { n: 16, title: 'Old-entity (BCC) Jun–Oct-25 movement 10,03,090 → 77,549 not fully evidenced', type: 'reconciliation-difference', amt: null, amtText: 'TBD', status: 'open', evidence: 'Receipt #1568 once shown 96,910 vs 1,00,000', action: 'Get Centre ledger Jun–Oct-25 to rule out double-counting' },
        { n: 17, title: 'FY26-27 balance unconfirmed — arithmetic accepted but NO signed reconciliation; NIL rebates vs ₹33L paid', type: 'balance-unconfirmed', amt: 0, status: 'verify', evidence: 'Naren 10-Jun-26 ledger print', action: 'Obtain signed statement + FY26-27 rebate JVs' },
      ],
    },
    {
      id: 'trinity',
      name: 'Trinity',
      sub: 'Trinity Cycles · Pargaon & Ludhiana',
      updated: '2026-07-07',
      lastReviewed: '2026-07-07',
      position:
        'No BCH ledger reconstructed yet. Only invoice TCI/P/26-27/1551 (Pargaon) reviewed — verdict is a BENEFIT: schemes honoured (~17.9% off BDP), free goods exact, no price inflation. Ludhiana invoice (~260 cycles, ₹15.2L BDP) not yet received. ⚠ Pay 1551 by 15-Jul-26 for 1% CD; before 30-Jul-26 to avoid 24% p.a. interest.',
      theirBal: { amount: null, label: 'No statement obtained yet' },
      ourBal: { amount: null, label: 'Ledger not reconstructed' },
      recov: { amount: 10211, text: '₹10,211 capturable 1% CD — deadline 15-Jul-2026' },
      deadline: { date: '2026-07-15', label: 'Pay inv 1551 for 1% CD (₹10,211); 24% p.a. interest from 30-Jul' },
      notes:
        'Terms: minimum billing ₹40K without GST; NO BILLING if outstanding > 60 days. Bank: Kotak A/c 9812447652, IFSC KKBK0001753. WhatsApp not yet mined; least-analysed brand.',
      entries: [],
      gaps: [
        { n: 1, title: 'Invoice 1551 billed 120 cycles vs "2-each" Pargaon order of 96 — 24 extra (Rocco/M500)', type: 'invoice-discrepancy', amt: null, amtText: '24-cycle variance (₹10,21,064 taxable billed)', status: 'verify', evidence: '15-Jun-26 invoice-review-1551 + order-2026-06-09.csv', action: 'Confirm 24 extra were ordered; if not, seek CN or return' },
        { n: 2, title: '30-day cash discount 1% still capturable if paid by 15-Jul-2026', type: 'discount-pending', amt: 10211, status: 'open', evidence: '15-Jun-26 invoice-review-1551 (CD slab)', action: 'PAY BEFORE 15-Jul-2026 to secure 1% CD' },
        { n: 3, title: 'Higher CD slabs lapsed: 1-day 4% (₹40,843), 10-day 2.5%, 20-day 1.5%', type: 'discount-pending', amt: null, amtText: '40,843 max, now lapsed', status: 'verify', evidence: 'Invoice 15-Jun; 22 days elapsed as of 07-Jul', action: 'Verify payment date vs slabs; document CD captured vs foregone' },
        { n: 4, title: 'After 45 days (30-Jul-26) Trinity charges 24% p.a. on overdue; billing blocked >60 days O/S', type: 'operational-warranty', amt: null, amtText: '24% p.a. from 30-Jul-26 if unpaid', status: 'open', evidence: 'Invoice terms + stock sheet headers', action: 'Clear invoice 1551 before 30-Jul-2026' },
        { n: 5, title: 'Ludhiana order (~260 cycles / 66 lines, ₹15,21,480 BDP) — no invoice received/reviewed', type: 'documentation-gap', amt: null, amtText: '₹15.21L order value', status: 'open', evidence: '09-Jun-26 order-2026-06-09.csv', action: 'Obtain Ludhiana invoice; review schemes like 1551' },
        { n: 6, title: 'No BCH ledger, no payments/receipts reconciled — overall Trinity balance unknown', type: 'balance-unconfirmed', amt: null, amtText: 'TBD', status: 'open', evidence: 'No ledger file in /trinity/', action: 'Reconstruct ledger from invoices, payments and bank' },
      ],
    },
  ],
}

// ---- Attach generated ledger threads + match metadata ----
// matchable: computed closing is comparable against theirBal (both sides loaded)
export const LEDGER_META = {
  lucifer: {
    matchable: true,
    note: 'BCH-built ledger (both sides) to 31-May-26 — ties BCH books ₹14,86,026. Brand 02-Jul-26 shows ₹18,48,717: Jun/Jul entries (LB/0363 ₹17.8L, 11-Jun ₹5L payment, DIS-99/100) not yet loaded — add from the 02-Jul ledger.',
  },
  cultsport: {
    matchable: true,
    note: 'Full history from Jan-2023 (GSTR-2B + AR memos + bank), ties BCH line-items ₹25,71,988. Diff vs brand ₹27,03,388 = gap #2 (CD/CN booked by BCH, not yet passed by brand).',
  },
  emotorad: {
    matchable: true,
    note: "EM's official Hub-folio (666) export, opening 01-Apr-25 implied ₹64,78,990 — ties official closing ₹88,87,251.90 exactly. theirBal ₹92,35,598 = Hub + BCC ₹3,48,346 (folio 121, not in this thread). 58 return-CNs flagged for gap #24 verification.",
  },
  aoki: {
    matchable: true,
    note: "Invoices + payments from AOKI snapshots — ties AOKI's ledger ₹8,12,960 exactly. Two Feb/Mar-26 payments dated provisionally (gap #10).",
  },
  raleigh: {
    matchable: false,
    note: 'BCH payments only (₹ out) — Naren-side invoices are Tally prints, not yet structured. Running total shows cumulative paid, not balance.',
  },
  hornback: {
    matchable: false,
    note: 'BCH payments only — 26 receipts totalling ₹22,07,603, ties the SOA received-total exactly. Invoice side not yet loaded.',
  },
  trinity: {
    matchable: false,
    note: 'Only invoice 1551 (taxable value) — no ledger reconstructed yet. Ludhiana invoice awaited.',
  },
}

for (const b of seedData.brands) {
  const g = genLedgers[b.id]
  if (g) {
    b.entries = g.entries
    b.ledger = { opening: g.opening, coverage: g.coverage, ...(LEDGER_META[b.id] || {}) }
  }
}
